name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install depencencies
      run: sudo apt-get install -y libxkbcommon-dev
    - name: Build
      run: cargo build --verbose
    - name: Run init test
      run: cargo test init --verbose
    - name: Run snapshot test
      run: cargo test snapshot --verbose
